modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cables_and_pipes"
version = "${version}"
displayName = "Cables & Pipes"
authors = "ezTxmMC"
description = '''

'''
#logoFile = ""

[[dependencies.cables_and_pipes]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cables_and_pipes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cables_and_pipes]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cables_and_pipes.mixins.json"
